# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/
# https://docs.travis-ci.com/user/conditional-builds-stages-jobs/
# https://docs.travis-ci.com/user/conditions-v1

# You can import up to 25 other configs in total.
os: linux

language: node_js

node_js:
  - 12

cache:
  - npm

script:
  - echo "helloworld"

jobs:
  include:
    # /home/logic/_workspace/travis-playlist/travis-build-merger/.travis.yml
    - stage: Merge
      script:
        - wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/master/travis-build-merger/merge_if_success.sh
        - bash merge_if_success.sh

import:
  - credentials.yml
  - hugo-helloworld/.travis.yml
  # - liva-hugo-tryout/.travis.yml