# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/
# https://docs.travis-ci.com/user/conditional-builds-stages-jobs/
# https://docs.travis-ci.com/user/conditions-v1

# You can import up to 25 other configs in total.
os: linux

language: node_js

node_js:
  - 12

cache:
  - npm

jobs:
  include:
    - stage: Build
      name: build (hugo-helloworld)
      script:
        - echo 'helloworld'

    - stage: Merge
      name: run merge
      if: branch != master
      script:
        -  sudo apt update
        -  sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
        -  python3 -m pip install pipenv

        - mkdir -p tmp
        - cd tmp
        -   wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/master/travis-build-merger/_util/merge.py
        -   wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/master/travis-build-merger/_util/Pipfile
        -   wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/master/travis-build-merger/_util/Pipfile.lock
        -   chmod +x merge.py

        -   pipenv sync
        -   pipenv run python3 ./merge.py
        - cd -


stages:
  - name: Unit_test
  - name: Test
  - name: Build
  - name: Deploy
    if: branch = master

  - name: Integration_to_other_repo
    if: branch = develop

  - name: Publish_dashboard
    if: branch = master

  - name: Merge
    if: branch != master

  - name: Cron


import:
  - credentials.yml
  - hugo-helloworld/.travis.yml
  - liva-hugo-tryout/.travis.yml