# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/
# https://docs.travis-ci.com/user/conditional-builds-stages-jobs/
# https://docs.travis-ci.com/user/conditions-v1

# You can import up to 25 other configs in total.
os: linux

language: node_js

node_js:
  - 12

cache:
  - npm

jobs:
  include:
    - stage: Build
      name: build (hugo-helloworld)
      script:
        - echo 'helloworld'

stages:
  - name: Unit_test
  - name: Test
  - name: Build
  - name: Deploy
    if: branch = master

  - name: Integration_to_other_repo
    if: branch = develop

  - name: Publish_dashboard
    if: branch = master

  - name: Merge
    if: branch != master

  - name: Cron


import:
  - credentials.yml
  - .travis-merger.yml
  - hugo-helloworld/.travis.yml
  - liva-hugo-tryout/.travis.yml