# baseURL = "https://louiscklaw.github.io/hugo-playlist/"

languageCode = "en-us"
title = "My New Hugo Site"
theme = "helloworld-theme"


[privacy]
  [privacy.disqus]
    disable = true

  [privacy.googleAnalytics]
    disable = true

  [privacy.instagram]
    disable = true

  [privacy.twitter]
    disable = true

  [privacy.vimeo]
    disable = true

  [privacy.youtube]
    disable = true
